from __future__ import annotations

from datetime import datetime
from typing import TypeAlias, Literal

from pydantic import (
    Field,
)

from graph_rag.model.base import (
    ContractModel,
    WorkflowStatus,
    WorkflowLimitsMode,
    NonEmptyStr
)
from graph_rag.utils import (
    new_id,
    utc_now
)


# =============================================================================
# QUESTION AND EXECUTION LIMITS
#
# Question identifies one workflow execution and carries the user text plus
# request-level limits. profile_id is an optional explicit profile selection;
# when omitted, initialization uses the configured GraphDataProfile.
# =============================================================================


class WorkflowLimits(ContractModel):
    """Specify request-level bounds for workflow execution.

    Attributes:
        max_iterations: Maximum number of investigation iterations allowed.
        max_elapsed_seconds: Maximum intended wall-clock duration in seconds.
        mode: Rule used to apply the configured limits.
    """

    max_iterations: int = Field(
        default=8,
        ge=1,
        description=(
            "Maximum number of investigation iterations permitted for this workflow. "
            "Treat this as an execution constraint supplied by the caller; copy it "
            "unchanged rather than choosing a new value."
        ),
    )
    max_elapsed_seconds: int = Field(
        default=120,
        ge=1,
        description=(
            "Maximum intended wall-clock duration, in seconds, for this workflow. Treat "
            "this as a caller-supplied execution constraint and do not revise it."
        ),
    )
    mode: WorkflowLimitsMode = Field(
        default=WorkflowLimitsMode.FIRST,
        description=(
            "Rule for deciding when configured limits stop execution. Use the exact "
            "supplied enum value and apply its documented semantics consistently."
        ),
    )


FinalAnswerStatus: TypeAlias = Literal[
    WorkflowStatus.COMPLETE,
    WorkflowStatus.PARTIAL,
    WorkflowStatus.FAILED,
]


class Question(ContractModel):
    """Represent the complete user request accepted by the workflow.

    Attributes:
        id: Stable identifier shared by the question and workflow execution.
        text: Natural-language question the workflow must answer.
        profile_id: Optional explicit graph-data profile identifier. When absent,
            initialization uses the process configuration.
        limits: Request-specific execution bounds and limit-resolution mode.
        submitted_at: UTC timestamp at which the question was created.
    """

    id: str = Field(
        default_factory=lambda: new_id("workflow"),
        description=(
            "Stable workflow identifier. It is normally generated by the application; "
            "omit it when creating a new question unless an existing workflow ID was "
            "explicitly supplied. Reuse this exact value throughout the workflow."
        ),
    )
    text: NonEmptyStr = Field(
        description=(
            "The original natural-language request to solve. Preserve the user’s meaning "
            "exactly; do not replace this field with an answer, summary, plan, or "
            "rewritten request."
        ),
    )
    profile_id: NonEmptyStr | None = Field(
        default=None,
        description=(
            "Optional exact graph-data profile identifier selected for this workflow, for "
            "example \"gtd/v1\". Use only a configured profile ID; do not invent one. Leave "
            "null when initialization should use the configured default profile."
        ),
    )
    limits: WorkflowLimits = Field(
        default_factory=WorkflowLimits,
        description=(
            "Caller-supplied workflow execution limits. Carry this object forward "
            "unchanged; it is not part of the investigation reasoning."
        ),
    )
    submitted_at: datetime = Field(
        default_factory=utc_now,
        description=(
            "UTC submission timestamp generated by the application. Omit it when creating "
            "a new question unless the exact timestamp is already known."
        ),
    )

    def simple_string(self) -> str:
        return f"Question: {self.text}"


class FinalAnswer(ContractModel):
    """Represent the public terminal response.

    Attributes:
        workflow_id: Identifier used to retrieve the persisted workflow record.
        status: Terminal workflow status represented by the response.
        answer: User-facing answer or clarification request.
        confidence: Confidence in the answer.
    """

    workflow_id: NonEmptyStr = Field(
        description=(
            "Exact workflow/question ID used to retrieve the persisted plan, evidence, "
            "raw results, and iteration trace. Copy it from GraphRagState.workflow_id."
        ),
    )
    status: FinalAnswerStatus = Field(
        description=(
            "Terminal workflow status. It must agree with the final action and latest "
            "evaluation; use COMPLETE only for a fully supported answer."
        ),
    )
    answer: NonEmptyStr = Field(
        description=(
            "Direct user-facing answer. Base factual claims on the accepted findings "
            "and evidence carried by the workflow, but do not expose internal IDs or "
            "raw trace data."
        ),
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description=(
            "Confidence in the answer, on a scale from 0 to 1. 0 means the answer is "
            "completely uncertain, while 1 means the answer is completely certain."
        ),
    )
