from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import (
    BeforeValidator,
    Field,
    model_validator,
    JsonValue,
)

from graph_rag.model.base import (
    ContractModel,
    ReasoningImpact,
    NonEmptyStr
)
from graph_rag.utils import (
    new_id,
    scalar_to_list,
    utc_now
)


# =============================================================================
# SUPPORTING DATA
#
# EvidenceData is the structure that holds the raw JSON data returned with a tool
# call result. These are provided to the LLM to create the EvidenceRecord summary.
# EvidenceRecord is an LLM-authored, prompt-friendly summary of one or more raw
# results. Subsequent reasoning carries evidence summaries rather than repeatedly
# copying raw result payloads into the model context.
# =============================================================================


class EvidenceData(ContractModel):
    """
    Represents the raw evidence data retrieved from a tool call result.

    This class is used to encapsulate evidence data generated by a tool call and its result,
    providing a stable identifier for referencing within the system. It captures metadata
    such as creation time and retains raw evidence data imported from tool-generated results.

    Attributes:
        id (str): Stable identifier for this raw evidence data. It is normally
            generated automatically; omit it when creating new evidence. Findings and other
            reasoning records cite this ID.
        tool_call_result_id (str): Stable identifier for the tool call result that generated
            this evidence.
        data (JsonValue): Raw data from the tool call result that generated this evidence.
        created_at (datetime): UTC timestamp at which the evidence record was created.
    """

    id: str = Field(
        default_factory=lambda: new_id("evidence"),
        description=(
            "Stable identifier for this raw evidence data. It is normally "
            "generated automatically; omit it when creating new evidence. Findings and "
            "other reasoning records cite this ID."
        ),
    )
    tool_call_result_id: NonEmptyStr = Field(
        description=(
            "Stable identifier for the tool call result that generated this evidence."
        ),
    )
    data: JsonValue = Field(
        description=(
            "Raw data from the tool call result that generated this evidence."
        ),
    )
    created_at: datetime = Field(
        default_factory=lambda: utc_now(),
        description=(
            "UTC timestamp at which the evidence record was created."
        ),
    )


class EvidenceRecord(ContractModel):
    """Carry a prompt-friendly interpretation of retained tool results.

    The LLM creates an evidence record after examining raw result data. The
    summary is the compact information carried forward for planning, evaluation,
    and answer generation. Raw data remains available through the referenced
    result IDs for verification or programmatic inspection.

    Attributes:
        id: Stable identifier referenced by findings and reasoning artifacts.
        summary: Concise textual interpretation of the relevant result data.
        evidence_data_ids: EvidenceData IDs supporting the summary.
        created_at: UTC timestamp at which the evidence record was created.
    """

    id: str = Field(
        default_factory=lambda: new_id("evidence"),
        description=(
            "Stable identifier for this compact evidence interpretation. It is normally "
            "generated automatically; omit it when creating new evidence. Findings and "
            "other reasoning records cite this ID."
        ),
    )
    summary: NonEmptyStr = Field(
        description=(
            "Concise, prompt-friendly interpretation of the relevant facts, values, "
            "relationships, or absence of data in the cited raw tool results. Include the "
            "information later reasoning needs; do not copy the full raw payload, merely "
            "report tool success, or add claims the results do not support."
        ),
    )
    evidence_data_ids: Annotated[
        list[NonEmptyStr],
        BeforeValidator(scalar_to_list),
    ] = Field(
        min_length=1,
        description=(
            "IDs of the retained EvidenceData objects actually examined to produce this "
            "summary. Cite data IDs only, include every materially used result, exclude "
            "unrelated results, and never substitute request or evidence IDs."
        ),
    )
    created_at: datetime = Field(
        default_factory=utc_now,
        description=(
            "UTC timestamp generated when this interpretation is created. Omit it for new "
            "evidence unless the application explicitly supplies the timestamp."
        ),
    )

    @model_validator(mode="after")
    def validate_source_results(self) -> EvidenceRecord:
        """Reject duplicate source-result identifiers."""

        if len(self.evidence_data_ids) != len(set(self.evidence_data_ids)):
            raise ValueError("evidence data ids must be unique")
        return self


class Contradiction(ContractModel):
    """Record a conflict discovered in evidence or accepted plan progress.

    Attributes:
        id: Stable contradiction identifier.
        description: Textual explanation of the conflicting information.
        rationale: Explanation of why the cited information is contradictory.
        impact: Effect of the contradiction on answer completion.
        evidence_record_ids: Evidence records demonstrating the conflict.
        affected_step_ids: Plan steps whose progress or findings are affected.
    """

    id: str = Field(
        default_factory=lambda: new_id("contradiction"),
        description=(
            "Stable identifier for this contradiction, normally generated automatically. "
            "Preserve it while tracking the same unresolved conflict."
        ),
    )
    description: NonEmptyStr = Field(
        description=(
            "Specific conflict between evidence summaries, findings, assumptions, or plan "
            "expectations. State both sides clearly enough that the conflict can be "
            "investigated."
        ),
    )
    rationale: NonEmptyStr = Field(
        description=(
            "Explain why the cited information is genuinely inconsistent or materially in "
            "tension and how that conflict affects the investigation."
        ),
    )
    impact: ReasoningImpact = Field(
        description=(
            "How strongly this contradiction disrupts answer completion. Use BLOCKING "
            "when a complete answer is unjustified until resolved, MATERIAL for "
            "substantial uncertainty, and SUPPORTING or MINOR for lower-impact conflicts."
        ),
    )
    evidence_record_ids: Annotated[
        list[NonEmptyStr],
        BeforeValidator(scalar_to_list),
    ] = Field(
        min_length=1,
        description=(
            "Exact EvidenceRecord IDs that demonstrate the conflicting information. Cite "
            "all material sides of the contradiction; do not use raw result or request "
            "IDs."
        ),
    )
    affected_step_ids: Annotated[
        list[NonEmptyStr],
        BeforeValidator(scalar_to_list),
    ] = Field(
        default_factory=list,
        description=(
            "Exact current-plan step IDs whose findings, status, or completion are "
            "affected by this contradiction."
        ),
    )
